language: php

before_install:
- pwd
- ls -al
- openssl aes-256-cbc -K $encrypted_2a3b7c31670d_key -iv $encrypted_2a3b7c31670d_iv -in travis.pem.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

script:
- curl -svo data http://dm4.tw/ip
- git config --global user.name "Automatic commit (travis-ci)"
- git config --global user.email "travic-ci@dm4.tw"
- git checkout master
- git add data
- git commit -m 'Automatic commit (travis-ci)'
- git remote add deploy git@github.com:dm4/travis-test.git
- git push deploy master
